CREATE DATABASE IF NOT EXISTS kecamatan_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE kecamatan_db;

CREATE TABLE users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(160) NOT NULL,
  role ENUM('admin') NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE site_settings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(80) NOT NULL UNIQUE,
  setting_value TEXT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE hero_slides (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NULL,
  subtitle VARCHAR(180) NULL,
  image_url VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE officials (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  position VARCHAR(160) NOT NULL,
  nip VARCHAR(40) NULL,
  photo_url VARCHAR(255) NULL,
  parent_id BIGINT UNSIGNED NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_official_parent FOREIGN KEY (parent_id) REFERENCES officials(id) ON DELETE SET NULL
);

CREATE TABLE profile_contents (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  type ENUM('welcome', 'tourism_intro') NOT NULL UNIQUE,
  title VARCHAR(180) NOT NULL,
  body TEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tourism_potentials (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  category VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  location VARCHAR(180) NULL,
  image_url VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tourism_points (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tourism_id BIGINT UNSIGNED NOT NULL,
  point_text VARCHAR(180) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_tourism_points_tourism FOREIGN KEY (tourism_id) REFERENCES tourism_potentials(id) ON DELETE CASCADE
);

CREATE TABLE services (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(160) NOT NULL,
  icon_class VARCHAR(120) NULL,
  description TEXT NULL,
  link_url VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE news (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NOT NULL,
  slug VARCHAR(240) NOT NULL UNIQUE,
  category ENUM('Berita Utama', 'Berita', 'Kegiatan', 'Pengumuman') NOT NULL DEFAULT 'Berita',
  summary TEXT NOT NULL,
  content LONGTEXT NOT NULL,
  image_url VARCHAR(255) NULL,
  published_date DATE NOT NULL,
  status ENUM('draft', 'published') NOT NULL DEFAULT 'published',
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_news_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_news_status_date (status, published_date),
  INDEX idx_news_category (category)
);

CREATE TABLE public_documents (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NOT NULL,
  category VARCHAR(120) NOT NULL,
  year YEAR NOT NULL,
  description TEXT NOT NULL,
  file_url VARCHAR(255) NOT NULL,
  status ENUM('draft', 'published') NOT NULL DEFAULT 'published',
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_documents_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_documents_status_year (status, year),
  INDEX idx_documents_category (category)
);

CREATE TABLE contacts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(120) NOT NULL,
  value_text VARCHAR(255) NOT NULL,
  icon_class VARCHAR(120) NULL,
  link_url VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE social_links (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  platform VARCHAR(80) NOT NULL,
  icon_class VARCHAR(120) NULL,
  url VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE survey_responses (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  respondent_name VARCHAR(160) NULL,
  service_type VARCHAR(180) NOT NULL,
  overall_rating TINYINT UNSIGNED NOT NULL,
  ease_rating TINYINT UNSIGNED NOT NULL,
  speed_rating TINYINT UNSIGNED NOT NULL,
  staff_rating TINYINT UNSIGNED NOT NULL,
  feedback TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_survey_created_at (created_at),
  INDEX idx_survey_service_type (service_type),
  CONSTRAINT chk_survey_overall_rating CHECK (overall_rating BETWEEN 1 AND 5),
  CONSTRAINT chk_survey_ease_rating CHECK (ease_rating BETWEEN 1 AND 5),
  CONSTRAINT chk_survey_speed_rating CHECK (speed_rating BETWEEN 1 AND 5),
  CONSTRAINT chk_survey_staff_rating CHECK (staff_rating BETWEEN 1 AND 5)
);
